// Copyright (c) 2021 Jose Torres. All rights reserved. Licensed under the Apache License, Version 2.0. See LICENSE.md file in the project root for full license information.
// <auto-generated>

namespace AudioDeviceSwitcher.Interop;

using System.Runtime.InteropServices;
using HRESULT = System.Int32;

public enum ERole
{
    eConsole = 0,
    eMultimedia = 1,
    eCommunications = 2,
}

public enum EDataFlow
{
    eRender = 0,
    eCapture = 1,
    eAll = 2,
}

public enum MMDeviceState
{
    Active = 0x00000001,
    Disabled = 0x00000002,
    NotPresent = 0x00000004,
    Unplugged = 0x00000008,
    All = 0x0000000f,
}

[Guid("F8679F50-850A-41CF-9C72-430F290290C8")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IPolicyConfig
{
    HRESULT _GetMixFormat();
    HRESULT _GetDeviceFormat();
    HRESULT _ResetDeviceFormat();
    HRESULT _SetDeviceFormat();
    HRESULT _GetProcessingPeriod();
    HRESULT _SetProcessingPeriod();
    HRESULT _GetShareMode();
    HRESULT _SetShareMode();
    HRESULT _GetPropertyValue();
    HRESULT _SetPropertyValue();
    HRESULT SetDefaultEndpoint(string deviceId, ERole role);
    HRESULT SetEndpointVisibility(string deviceId, int value);
}

[ComImport]
[Guid("870AF99C-171D-4F9E-AF0D-E63DF40C2BC9")]
public sealed class PolicyConfig
{
}

[Guid("D666063F-1587-4E43-81F1-B948E807363F")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public unsafe interface IMMDevice
{
    public HRESULT Activate(ref Guid id, uint dwClsCtx, IntPtr pActivationParams, [MarshalAs(UnmanagedType.IUnknown)] out object ppInterface);
    public HRESULT OpenPropertyStore(uint stgmAccess, out IPropertyStore ppProperties);
    public HRESULT GetId([MarshalAs(UnmanagedType.LPWStr)] out string id);
    public HRESULT GetState(out MMDeviceState pdwState);
};

[Guid("0BD7A1BE-7A1A-44DB-8397-CC5392387B5E")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public unsafe interface IMMDeviceCollection
{
    public HRESULT GetCount(out uint pcDevices);
    public HRESULT Item(uint nDevice, out IMMDevice ppDevice);
};

[Guid("A95664D2-9614-4F35-A746-DE8DB63617E6")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public unsafe interface IMMDeviceEnumerator
{
    public HRESULT EnumAudioEndpoints(EDataFlow dataFlow, uint dwStateMask, out IMMDeviceCollection ppDevices);
    public HRESULT GetDefaultAudioEndpoint(EDataFlow dataFlow, ERole role, out IMMDevice ppEndpoint);
    public HRESULT GetDevice(string id, out IMMDevice device);
}

[ComImport]
[Guid("BCDE0395-E52F-467C-8E3D-C4579291692E")]
public sealed class MMDeviceEnumerator
{
}

[Guid("886d8eeb-8cf2-4446-8d02-cdba1dbdcf99")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IPropertyStore
{
    int GetCount(out int cProps);
    int GetAt(int property, out PropertyKey pkey);
    int GetValue(ref PropertyKey key, out PropVariant pv);
    int SetValue(ref PropertyKey key, ref PropVariant propvar);
    int Commit();
}

public struct PropertyKey
{
    public Guid formatId;
    public int propertyId;
    public PropertyKey(Guid formatId, int propertyId)
    {
        this.formatId = formatId;
        this.propertyId = propertyId;
    }
}

[StructLayout(LayoutKind.Explicit)]
public struct PropVariant
{
    [FieldOffset(0)] public short type;
    [FieldOffset(8)] public IntPtr pointerValue;

#pragma warning disable CS0618 // Type or member is obsolete
    public T GetValueOrDefault<T>(T def = default)
    {
        if ((VarEnum)type == VarEnum.VT_EMPTY)
            return def;
        if ((VarEnum)type == VarEnum.VT_LPWSTR)
            return (T)(object)Marshal.PtrToStringUni(pointerValue);
        throw new NotImplementedException("Unsupported PropVariant: " + (VarEnum)type);
    }
#pragma warning restore CS0618 // Type or member is obsolete

    public static void Clear(ref PropVariant ptr)
    {
        Ole32.PropVariantClear(ref ptr);
    }
}

public static class MMDeviceConstants
{
    public static readonly PropertyKey KEY_Device_FriendlyName = new(new Guid(unchecked((int)0xa45c254e), unchecked((short)0xdf1c), 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0), 14);
    public const uint DEVICE_STATEMASK_ALL = 0x0000000fu;
    public const uint DEVICE_STATE_ACTIVE = 0x00000001;
    public const uint DEVICE_STATE_DISABLED = 0x00000002;
    public const uint DEVICE_STATE_NOTPRESENT = 0x00000004;
    public const uint DEVICE_STATE_UNPLUGGED = 0x00000008;
}

public static class StorageConstants
{
    public const uint STGM_READ = 0x00000000u;
}